apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: simplyfi
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: cm9vdA==     # base64("root")
  MONGO_INITDB_ROOT_PASSWORD: ZXhhbXBsZQ== # base64("example")

