apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
  namespace: simplyfi
data:
  MONGO_INITDB_DATABASE: "bezkoder_db"
  MONGO_HOST: "mongodb"
  MONGO_PORT: "27017"
  MONGODB_URI: "mongodb://root:example@mongodb:27017/bezkoder_db?authSource=admin"
